version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 10080:3306
    environment:
      - MYSQL_DATABASE=student_target
      - MYSQL_ROOT_PASSWORD=123123
    container_name: st_mysql
  app:
    build: .
    ports:
      - 10090:80
      - 10070:7000
    container_name: st_app
    depends_on:
      - mysql
    links:
      - mysql:mysql